# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sopsctl < Formula
  desc "SOPS profile manager - manage age key profiles for encryption"
  homepage "https://github.com/enbiyagoral/sopsctl"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enbiyagoral/sopsctl/releases/download/v0.3.1/sopsctl_0.3.1_darwin_amd64.tar.gz"
      sha256 "251f9d642f79f9e7b1445a4488a1dd76c3215ff5c24db25b0dcf0feea86fb966"

      def install
        bin.install "sopsctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enbiyagoral/sopsctl/releases/download/v0.3.1/sopsctl_0.3.1_darwin_arm64.tar.gz"
      sha256 "e7b26f795f56c19d7b6b09829335f4493492590cfa2caa2714c9094a3cf65275"

      def install
        bin.install "sopsctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsctl/releases/download/v0.3.1/sopsctl_0.3.1_linux_amd64.tar.gz"
      sha256 "d94de55ba0da8f42c2dd5c27828445c7ee3cf16558f9e8bbbaebfad4cf4239b2"
      def install
        bin.install "sopsctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsctl/releases/download/v0.3.1/sopsctl_0.3.1_linux_arm64.tar.gz"
      sha256 "c4b758f903a9784e13906077d91d0bbbfb5729cd05826c80ed3ab6400f0c99a9"
      def install
        bin.install "sopsctl"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration, run:
        sopsctl init zsh

      Then restart your terminal or run:
        source ~/.zshrc
    EOS
  end

  test do
    system "#{bin}/sopsctl", "--help"
  end
end
