# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sopsy < Formula
  desc "SOPS profile manager - manage age key profiles for encryption"
  homepage "https://github.com/enbiyagoral/sopsy"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.5.0/sopsy_0.5.0_darwin_amd64.tar.gz"
      sha256 "2280d2be0aed79fef75b76decae43a01115cf3d5f67a53f2f2b50c2292fb74d5"

      def install
        bin.install "sopsy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.5.0/sopsy_0.5.0_darwin_arm64.tar.gz"
      sha256 "30ea0990a0909584c4141f95accc5f0c4133a070eb386e733604599c8453cd7c"

      def install
        bin.install "sopsy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.5.0/sopsy_0.5.0_linux_amd64.tar.gz"
      sha256 "08ec4eed74bdff966659966400178459520231e351b1334b836793949259fb57"
      def install
        bin.install "sopsy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.5.0/sopsy_0.5.0_linux_arm64.tar.gz"
      sha256 "afb51df083f97e474e59b666aaa369908fc6bee333c41c6517e78cb715f3fd37"
      def install
        bin.install "sopsy"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration, run:
        sopsy init zsh

      Then restart your terminal or run:
        source ~/.zshrc
    EOS
  end

  test do
    system "#{bin}/sopsy", "--help"
  end
end
