# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sopsy < Formula
  desc "SOPS profile manager - manage age key profiles for encryption"
  homepage "https://github.com/enbiyagoral/sopsy"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.4.0/sopsy_0.4.0_darwin_amd64.tar.gz"
      sha256 "94c5ae74a1a9a7cebe7af5413ee5ddd450381fe93351c8da8c03d1da9d90111d"

      def install
        bin.install "sopsy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.4.0/sopsy_0.4.0_darwin_arm64.tar.gz"
      sha256 "8a1b8ecd84f4d8e7ffb24ed6666cbbb3c0b92373e972ca93ca6d6810c2e05d8e"

      def install
        bin.install "sopsy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.4.0/sopsy_0.4.0_linux_amd64.tar.gz"
      sha256 "30d94addcee38826512512fe816d46149cd62bdaf8ee04a2ffec698500bb16c1"
      def install
        bin.install "sopsy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.4.0/sopsy_0.4.0_linux_arm64.tar.gz"
      sha256 "67f245d12efd200a3fec3135d37e5eb71085fcda307f9b30c701243eaf4206d1"
      def install
        bin.install "sopsy"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration, run:
        sopsy init zsh

      Then restart your terminal or run:
        source ~/.zshrc
    EOS
  end

  test do
    system "#{bin}/sopsy", "--help"
  end
end
