# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sopsctl < Formula
  desc "SOPS profile manager - select profiles for encryption with fzf"
  homepage "https://github.com/enbiyagoral/sopsctl"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enbiyagoral/sopsctl/releases/download/v0.1.0/sopsctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "ff23a5567d356a7aeff634bec2f60555ce2f49242eb6a4057778c01a13f616b4"

      def install
        bin.install "sopsctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enbiyagoral/sopsctl/releases/download/v0.1.0/sopsctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "25c9b98df43bb23da73c7f402d6697f8633a4da3af61a9e223077a97199766e6"

      def install
        bin.install "sopsctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsctl/releases/download/v0.1.0/sopsctl_0.1.0_linux_amd64.tar.gz"
      sha256 "a0712653d383f1a8e2c2ac119c1b687d815f8e7d411d131674909532efae24bb"
      def install
        bin.install "sopsctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsctl/releases/download/v0.1.0/sopsctl_0.1.0_linux_arm64.tar.gz"
      sha256 "9c33ead2b11530e74220b57340851c476848f655b8d34fdb50f897abdcc03d4d"
      def install
        bin.install "sopsctl"
      end
    end
  end

  test do
    system "#{bin}/sopsctl", "--help"
  end
end
