# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sopsy < Formula
  desc "SOPS profile manager - manage age key profiles for encryption"
  homepage "https://github.com/enbiyagoral/sopsy"
  version "0.3.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.3.3/sopsy_0.3.3_darwin_amd64.tar.gz"
      sha256 "5782a83672827a0d92787f87265a3f026e8b58db76d5ee694ecd9df2a3e447bc"

      def install
        bin.install "sopsy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.3.3/sopsy_0.3.3_darwin_arm64.tar.gz"
      sha256 "10d193107cceed901dda087b8a8eedeb08191b3ba66d8fc379361d0bfe0cf788"

      def install
        bin.install "sopsy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.3.3/sopsy_0.3.3_linux_amd64.tar.gz"
      sha256 "44d71846e359154c897f85cc5638f778b9d40c4ae401106ae2c21193974f213f"
      def install
        bin.install "sopsy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbiyagoral/sopsy/releases/download/v0.3.3/sopsy_0.3.3_linux_arm64.tar.gz"
      sha256 "aa6983f780e8581ef46600c3c35eacb3bb052963a2260b3926f10caa1d3ada70"
      def install
        bin.install "sopsy"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration, run:
        sopsy init zsh

      Then restart your terminal or run:
        source ~/.zshrc
    EOS
  end

  test do
    system "#{bin}/sopsy", "--help"
  end
end
